### ISSUE TITLE
InitialState fetch data from Firebase 

### ISSUE THREAD

**Issue by anhbaysgalan1** [maechabin/traveling-salesman-demo#8]
Hello initialState routes[] needs from Firebase firestore database. can you help for create new branch?

**Comment by maechabin** [comment]
@anhbaysgalan1 

Thank you for your message. I also read the mail & FB message you sent me. 

> Hello initialState routes[] needs from Firebase firestore database. can you help for create new branch?

No problem. Feel free to fork this repository and create branch yourself as you like.

This is a React + Firebase (Firestore) sample repository I created. Please refer to it if you need.
https://github.com/maechabin/react-firebase-sample

If you have any questions, please feel free to ask.

**Comment by anhbaysgalan1** [comment]
Thank you for your reply. I will create new branch ;)
